services:
  vault:
    image: hashicorp/vault
    container_name: movienight-vault
    cap_add:
      - IPC_LOCK
    command: >
      server -dev
      -dev-root-token-id=${VAULT_TOKEN}
      -dev-listen-address=0.0.0.0:8200
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ./vault/policies:/vault/policies:ro
    networks:
      - edge
      - app_internal

  app:
    build: .
    command: uvicorn --app-dir src movienight.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      SQLITE_PROXY_URL: ${SQLITE_PROXY_URL}
    depends_on:
      - sqlite-proxy
    networks:
      - edge
      - app_internal

  sqlite-proxy:
    build: .
    command: uvicorn --app-dir src proxy.main:app --host 0.0.0.0 --port 9000
    expose:
      - "9000"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      CONJUR_BASE_URL: https://proxy:443
      CONJUR_ACCOUNT: myConjurAccount
      CONJUR_LOGIN_FOR_PROXY: host/sqlite-policy/database-proxy
      CONJUR_CERT_FILE: /etc/conjur-tls/nginx.crt
    depends_on:
      - vault
    volumes:
      - ./src/proxy/conjur_token:/app/src/proxy/conjur_token:ro
      - ./infra/conjur/conf/tls/nginx.crt:/etc/conjur-tls/nginx.crt:ro
      - ./data:/data
    networks:
      - app_internal
      - conjur_link

networks:
  edge: {}
  app_internal:
    internal: true
  conjur_link:
    external: true
    name: movienight-conjur_default