services:
  vault:
    image: hashicorp/vault
    container_name: movienight-vault
    cap_add:
      - IPC_LOCK
    command: >
      server -dev
      -dev-root-token-id=${VAULT_TOKEN}
      -dev-listen-address=0.0.0.0:8200
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      SKIP_SETCAP: "true"
      SKIP_CHOWN: "true"
    volumes:
      - ./vault/policies:/vault/policies:ro
    networks:
      - edge
      - app_internal

  vault-init:
    image: hashicorp/vault
    depends_on:
      - vault
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
    command: >
      sh -c "
        sleep 5
        vault secrets list | grep -q '^transit/' || vault secrets enable transit
        # vault policy write sqlite-key /vault/policies/sqlite-key-policy.hcl
      "
    networks:
      - app_internal
    restart: "no"

  app:
    build: .
    command: uvicorn --app-dir src movienight.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      SQLITE_PROXY_URL: ${SQLITE_PROXY_URL}
    depends_on:
      - sqlite-proxy
    networks:
      - edge
      - app_internal

  sqlite-proxy:
    build: .
    command: uvicorn --app-dir src proxy.main:app --host 0.0.0.0 --port 9000
    expose:
      - "9000"
    ports:  # THIS IS ONLY FOR DEMONSTRATION PURPOSES AND DOES NOT VIOLATE THE PoC
      - "9000:9000"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
    depends_on:
      - vault
      - vault-init
    volumes:
      - ./src/proxy/conjur_token:/app/src/proxy/conjur_token:ro
      - ./data:/data
    networks:
      - app_internal

networks:
  edge: {}
  app_internal:
    external: true